import torch
from ultralytics import YOLO
import cv2
import json

# 1. Verify ROCm GPU Acceleration
print("=== ZameenEye-AI Spatial Engine ===")
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
print(f"Targeting Compute Hardware: {torch.cuda.get_device_name(0) if device != 'cpu' else 'CPU'}")

# 2. Load the Weights Generated by your AMD Training Run
model = YOLO("runs/detect/train/weights/best.pt")

# Mock PostGIS Bounds Metadata for the Satellite Raster Layer
# In production, this data maps to your PostGIS GIST geometry indices
raster_metadata = {
    "image_path": "test_satellite_grid.jpg", 
    "top_left_lat": 31.5204,
    "top_left_lon": 74.3587,
    "bottom_right_lat": 31.4704,
    "bottom_right_lon": 74.4087,
    "pixel_width": 1024,
    "pixel_height": 1024
}

print(f"Ingesting raster layer. Resolving bounding box coordinates via PostGIS matrix map...")

# 3. Execute ROCm-Resident Object Detection
# Passing device=0 forces the tensor matrices straight to the AMD Compute Units
results = model(raster_metadata["image_path"], device=0)

spatial_alerts = []

# 4. Map Image Pixels back to Real-World PostGIS Geospatial Coordinates
for result in results:
    boxes = result.boxes.xyxy.cpu().numpy()  # Extract bounding boxes
    classes = result.boxes.cls.cpu().numpy()
    
    for box, cls in zip(boxes, classes):
        x1, y1, x2, y2 = box
        # Calculate center pixel of the hotspot
        center_x = (x1 + x2) / 2
        center_y = (y1 + y2) / 2
        
        # Linear interpolation to translate pixels to GPS Coordinates
        lon_pct = center_x / raster_metadata["pixel_width"]
        lat_pct = center_y / raster_metadata["pixel_height"]
        
        target_lon = raster_metadata["top_left_lon"] + lon_pct * (raster_metadata["bottom_right_lon"] - raster_metadata["top_left_lon"])
        target_lat = raster_metadata["top_left_lat"] - lat_pct * (raster_metadata["top_left_lat"] - raster_metadata["bottom_right_lat"])
        
        alert = {
            "hazard_type": "Wildfire Hotspot" if int(cls) == 0 else "Anomalous Thermal Sign",
            "geom": f"SRID=4326;POINT({target_lon:.6f} {target_lat:.6f})",
            "confidence": float(result.boxes.conf[0])
        }
        spatial_alerts.append(alert)

# 5. Output the Payloads ready for the Multi-Tenant Backend Layer
print("\n=== Verified PostGIS Ingestion Payload ===")
print(json.dumps(spatial_alerts, indent=2))
